# generated by {burglr}

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# find_astar (copied from pavo:::find_astar)
# from pavo 2.7.0
`find_astar` <- function(coords) {
  tetras <- alphashape3d::ashape3d(coords, alpha = 0)$tetra
  tetras <- cbind(c(tetras[, c("v1", "v2", "v3", "v4")]), rep(tetras[
    ,
    "rhoT"
  ], 4))
  astar <- max(by(tetras[, 2], tetras[, 1], min))
  message("'avalue' automatically set to ", sprintf(
    "%.4e",
    astar * (1 + 1e-15)
  ))
  return(astar * (1 + 1e-15))
}
